spring.application.name=impact-radar-backend

spring.datasource.url=jdbc:postgresql://localhost:15432/impact_radar
spring.datasource.username=impact_radar
spring.datasource.password=impact_radar
spring.datasource.driver-class-name=org.postgresql.Driver
